[workspace]
resolver = "2"
members = [
    "bins/web-server",
    "crates/libs/handlers", 
    "crates/libs/routes", 
    "crates/libs/database",
]


[workspace.dependencies]
axum = "0.8.3"
tokio = { version = "1.36", features = ["full"] }

