[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
handlers = { path = "../libs/handlers" }
routes =  { path = "../libs/routes" }
database = { path = "../libs/database" }
axum.workspace = true
tokio.workspace = true

