[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
pulse_database.workspace = true
pulse_handlers.workspace = true
pulse_routes.workspace = true
axum.workspace = true
tokio.workspace = true

teloxide.workspace = true
